# Generated by Django 4.0.3 on 2023-05-05 13:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MR', verbose_name='الهاتف'),
        ),
    ]
