# Generated by Django 4.0.3 on 2023-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_isc_topic_delete_hopital_alter_donneur_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='isc',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%y/%m/%d', verbose_name='صورة'),
            preserve_default=False,
        ),
    ]
