# Generated by Django 4.0.3 on 2023-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_topic_options_alter_isc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='isc',
            name='location',
            field=models.CharField(default=1, max_length=50, verbose_name='الموقع'),
            preserve_default=False,
        ),
    ]
